name = "dome"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

routes = [
  { pattern = "dome.rameshkumar.space", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
